#!/usr/bin/env bash
# Stops the 4-to_infinity_and_beyond process without using kill or killall

# Find PID(s) of the running script
for pid in $(ps -ef | grep '4-to_infinity_and_beyond' | grep -v grep | awk '{print $2}'); do
    # Send SIGTERM using built-in kill
    kill "$pid"
done
