#!/usr/bin/env bash
# Infinite loop that handles SIGTERM by displaying "I am invincible!!!"

# Handle SIGTERM
trap 'echo "I am invincible!!!" >&2' SIGTERM

# Infinite loop
while true; do
    echo "To infinity and beyond"
    sleep 2
done
