#!/usr/bin/env bash
# Displays different messages on 4th and 8th iteration, "Best School" otherwise
count=1
while [ $count -le 10 ]; do
  if [ $count -eq 4 ]; then
    echo "bad luck"
  elif [ $count -eq 8 ]; then
    echo "good luck"
  else
    echo "Best School"
  fi
  count=$((count + 1))
done
