#!/usr/bin/env bash
# Displays numbers 1-20; special "bad luck" messages for 4, 9, 17
count=1
while [ $count -le 20 ]; do
  case $count in
    4) echo "4"; echo "bad luck from China";;
    9) echo "9"; echo "bad luck from Japan";;
    17) echo "17"; echo "bad luck from Italy";;
    *) echo "$count";;
  esac
  count=$((count + 1))
done
